// Trimmed version of braids/settings.h.
//
// The original file describes the full UI / firmware persistence surface of
// the Mutable Instruments Braids module (menu order, save format, hardware
// calibration, etc.). For the in-tree DSP port we only need the
// MacroOscillatorShape enum — the rest is hardware-only and intentionally
// omitted.

#ifndef BRAIDS_SETTINGS_H_
#define BRAIDS_SETTINGS_H_

#include "stmlib_compat.h"

namespace braids {

enum MacroOscillatorShape {
	MACRO_OSC_SHAPE_CSAW,
	MACRO_OSC_SHAPE_MORPH,
	MACRO_OSC_SHAPE_SAW_SQUARE,
	MACRO_OSC_SHAPE_SINE_TRIANGLE,
	MACRO_OSC_SHAPE_BUZZ,

	MACRO_OSC_SHAPE_SQUARE_SUB,
	MACRO_OSC_SHAPE_SAW_SUB,
	MACRO_OSC_SHAPE_SQUARE_SYNC,
	MACRO_OSC_SHAPE_SAW_SYNC,
	MACRO_OSC_SHAPE_TRIPLE_SAW,
	MACRO_OSC_SHAPE_TRIPLE_SQUARE,
	MACRO_OSC_SHAPE_TRIPLE_TRIANGLE,
	MACRO_OSC_SHAPE_TRIPLE_SINE,
	MACRO_OSC_SHAPE_TRIPLE_RING_MOD,
	MACRO_OSC_SHAPE_SAW_SWARM,
	MACRO_OSC_SHAPE_SAW_COMB,
	MACRO_OSC_SHAPE_TOY,

	MACRO_OSC_SHAPE_DIGITAL_FILTER_LP,
	MACRO_OSC_SHAPE_DIGITAL_FILTER_PK,
	MACRO_OSC_SHAPE_DIGITAL_FILTER_BP,
	MACRO_OSC_SHAPE_DIGITAL_FILTER_HP,
	MACRO_OSC_SHAPE_VOSIM,
	MACRO_OSC_SHAPE_VOWEL,
	MACRO_OSC_SHAPE_VOWEL_FOF,

	MACRO_OSC_SHAPE_HARMONICS,

	MACRO_OSC_SHAPE_FM,
	MACRO_OSC_SHAPE_FEEDBACK_FM,
	MACRO_OSC_SHAPE_CHAOTIC_FEEDBACK_FM,

	MACRO_OSC_SHAPE_PLUCKED,
	MACRO_OSC_SHAPE_BOWED,
	MACRO_OSC_SHAPE_BLOWN,
	MACRO_OSC_SHAPE_FLUTED,
	MACRO_OSC_SHAPE_STRUCK_BELL,
	MACRO_OSC_SHAPE_STRUCK_DRUM,
	MACRO_OSC_SHAPE_KICK,
	MACRO_OSC_SHAPE_CYMBAL,
	MACRO_OSC_SHAPE_SNARE,

	MACRO_OSC_SHAPE_WAVETABLES,
	MACRO_OSC_SHAPE_WAVE_MAP,
	MACRO_OSC_SHAPE_WAVE_LINE,
	MACRO_OSC_SHAPE_WAVE_PARAPHONIC,

	MACRO_OSC_SHAPE_FILTERED_NOISE,
	MACRO_OSC_SHAPE_TWIN_PEAKS_NOISE,
	MACRO_OSC_SHAPE_CLOCKED_NOISE,
	MACRO_OSC_SHAPE_GRANULAR_CLOUD,
	MACRO_OSC_SHAPE_PARTICLE_NOISE,

	MACRO_OSC_SHAPE_DIGITAL_MODULATION,

	MACRO_OSC_SHAPE_808,

	MACRO_OSC_SHAPE_QUESTION_MARK,
	MACRO_OSC_SHAPE_LAST,
	MACRO_OSC_SHAPE_LAST_ACCESSIBLE_FROM_META = MACRO_OSC_SHAPE_DIGITAL_MODULATION
};

}  // namespace braids

#endif  // BRAIDS_SETTINGS_H_
